### ISSUE TITLE
HTTP ERROR 500 on plugin activation

### ISSUE THREAD

**Issue by s-oehding** [shyim/shopware-profiler#11]
installation went fine but when I try to activate the plugin I get this:

`PHP Warning: require_once(/var/www/shopware/custom/plugins/ShyimProfiler/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/shopware/custom/plugins/ShyimProfiler/ShyimProfiler.php on line 40`

`PHP Fatal error: require_once(): Failed opening required '/var/www/shopware/custom/plugins/ShyimProfiler/vendor/autoload.php' (include_path='/var/www/shopware/engine/Library:.:/usr/share/php') in /var/www/shopware/custom/plugins/ShyimProfiler/ShyimProfiler.php on line 40`

**Comment by shyim** [comment]
You must run `composer install` in the Plugin Directory to install the dependencies

**Comment by s-oehding** [comment]
Ok thank you!
