### ISSUE TITLE
[HTTP ERROR 500] Shopware 5.2.1 is not repsonding

### ISSUE THREAD

**Issue by mioga-brian** [shyim/shopware-profiler#13]
Hello, 

nice Plugin but, when I install and activate the Plugin Shopware Frontend/Backend Version 5.2.1 is not responding with the status code: HTTP ERROR 500.

I installed the plugin with this following commands:

> cd /var/www/..../shopware/
> git clone repository.git custom/plugins/ ShyimProfiler
> php /bin/console sw:plugin:refresh
> php /bin/console sw:plugin:install --activate  ShyimProfiler

**Comment by shyim** [comment]
You must run `composer install` in the Plugin Directory to install the dependencies

**Comment by shyim** [comment]
Or use the package from https://github.com/shyim/shopware-profiler/releases

**Comment by mioga-brian** [comment]
Thanks, yes i missed to run composer install. 
Sorry, for the trouble now it works well.
