### ISSUE TITLE
Admin Access

### ISSUE THREAD

**Issue by mbdesign** [shyim/shopware-profiler#24]
Is it possible to add a function to show the profiler just when the admin is logged id.

Maybe you can also add a IP field for it to use just profile for the written IP's

Thanks  and great tool!

**Comment by shyim** [comment]
IP field is already available on the newest version

Show only when backend user is logged in, is not so easy, because shopware has different sessions between frontend and backend. I will look for a solution

**Comment by shyim** [comment]
Backend and Frontend are different, so its not possible to check is the user in backend loggedin. You can use instead ip limitations
