### ISSUE TITLE
Usage on localhost

### ISSUE THREAD

**Issue by Isengo1989** [shyim/shopware-profiler#29]
@shyim 

Using the plugin on **localhost** and added the IP 127.0.0.1 - but nothing displays.

Already compiled the themes (Multishop) and cleared all caches. Any ideas? I do not get an Error in the Firebug Console neither a PHP Error.

best regards

**Comment by shyim** [comment]
Which shopware version are you using? Have you tried to disable other plugins?

**Comment by Isengo1989** [comment]
It works now, I added the ::1 to the hosts and cleared the Cache again.

My Version is 5.2.15. Now I see the toolbar, but when I press anything to see details on template etc. I get:

> [XXXX] PHP Fatal error:  Class 'Symfony\Component\VarDumper\Dumper\HtmlDumper' not found in /var/www/XXXX/custom/plugins/ShyimProfiler/Components/SmartyExtensions.php on line 31

**Comment by shyim** [comment]
I have updated the Release zip, can you try again?

**Comment by Isengo1989** [comment]
Backend and Frontend are down now :-/

**Comment by shyim** [comment]
Have you used https://github.com/shyim/shopware-profiler/releases/download/1.0.7/ShyimProfiler-1.0.7.zip ?. I have tested it on my online dev and it works fine

**Comment by Isengo1989** [comment]
@shyim works now! I accidentally downloaded the wrong zip.

I guess the /vendor Folder was missing. Since this was the only change. Is the VarDumper etc. standard in some SW5.2 installations?

**Comment by shyim** [comment]
it's a custom dependency of the plugin :)
