### ISSUE TITLE
Classes should use a Vendor Namespace

### ISSUE THREAD

**Issue by bcremer** [shyim/shopware-profiler#3]
To prevent duplicate classnames every Plugin should Prefix the Namespace with a unique Vendor Prefix.

We at Shopware are using "Swag" as our prefix, so our Namespace always starts with "Swag", like "SwagProfiler", "SwagAboCommerce" etc.

Please consider using "ShyimProfiler" as your plugin name.

Nevertheless very cool project and thank you for playing around with the Shopware 5.2 Beta :+1:

**Comment by shyim** [comment]
I will replace the Namespace later. Thanks

**Comment by Haehnchen** [comment]
+1 :)
