### ISSUE TITLE
Cache folder very big

### ISSUE THREAD

**Issue by cs-mitho** [shyim/shopware-profiler#30]
Really like this plugin, it helps a lot developing my own plugins.

But as I just observed, you're using your own cache folder in var/cache/production_xxxxx. Inside there are many more subfolders which weighed almost 1 GB of space. I can't remember how long I used this tool in my current project, but I imagine a lot of space wasted using your plugin in all my projects. 

Can you implement a log rotate and a setting for the backend to restrict the cache to  a certain amount? That would be much appreciated!

**Comment by shyim** [comment]
It is a good point. I will add a config with max profile limitations and add the cache to the shopware default performance module to discover the cache and clear :)

**Comment by cs-mitho** [comment]
That would be great, thanks!

**Comment by shyim** [comment]
Fixed in Plugin version 1.0.8

**Comment by cs-mitho** [comment]
Thanks, that was fast!

I downloaded the latest version and updated it from inside the plugin manager. Though it seemed to work, I got this error while updating:

```
An exception occurred while executing 'INSERT INTO s_core_config_elements (name, value, description, label, type, required, position, scope, options, form_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["maxProfiles", "i:50;", "You can disable it with 0 amount", "Max amount profiles, which should be saved", "number", 0, 0, 0, "a:0:{}", 294]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '294-maxProfiles' for key 'form_id_2'
```

Nevertheless it seems to work. I set the max value to 5 and surfed a little bit through the shop. Then I looked inside the cache folders an saw that there were eight files. Shouldn't there be just five? Surely it's not a big deal, but maybe you should have an eye on it.

But thanks for this great tool 👍

**Comment by shyim** [comment]
The index is also in cache. It holds a array of all profiles. I am working in develop branch to replace it with a sql table and make filters work :)
