### ISSUE TITLE
html comments in robots.txt

### ISSUE THREAD

**Issue by cs-mitho** [shyim/shopware-profiler#37]
Since the robots.txt is also a template file, I just noticed, that html comments are written in there as well.
I think that should best be avoided.

**Comment by shyim** [comment]
Its should be also broken in sitemap.xml

**Comment by cs-mitho** [comment]
What do you mean with "broken"?

**Comment by shyim** [comment]
nevermind :)
Its fixed, i will publish next days a new release

**Comment by cs-mitho** [comment]
Great, thanks!
