### ISSUE TITLE
Profiler breaks controller auto-registration

### ISSUE THREAD

**Issue by mmergenthaler** [shyim/shopware-profiler#38]
When this plugin is installed and activated, then the auto-registration of plugin controllers no longer works. I think because of missing method map entry "'events' => 'getEventsService'" in compiled DI container.

**Comment by shyim** [comment]
Shopware registers the controllers after plugin build method :/ (https://github.com/shopware/shopware/blob/5.2/engine/Shopware/Kernel.php#L745)
I will try search a another solution
