### ISSUE TITLE
does it work with custom templates?

### ISSUE THREAD

**Issue by kritop** [shyim/shopware-profiler#39]
it works turning on the responsive template but not with our custom template? where does it append to?

**Comment by shyim** [comment]
Hey,

the toolbar will be appended to the body before shopware sends the response to the client.
Is your </body> tag correct see https://github.com/shyim/shopware-profiler/blob/master/Subscriber/Collector.php#L180

**Comment by kritop** [comment]
we're having a JS issue:
http://look.neta.io/jSTt
you can see it here:

https://pw.koffein.io/checkout/confirm

**Comment by shyim** [comment]
Have you removed the shopware default csrf js classes?

**Comment by kritop** [comment]
if you check window.CSRF they are there, i am thinking right now it has to do with loading order?

**Comment by shyim** [comment]
Are you initializing csrf later like document ready?

**Comment by kritop** [comment]
would it change the profilers behaviour wrapping the "var window.CSRF._ajaxBeforeSend;" part into document.ready?

**Comment by shyim** [comment]
I tested it with DOMContentLoaded event, and it was too late, the emotion request was already send.
I would like surround it with a if to catch the error, but subrequests wouldn't be profiled on your page.

I will embed the profiler bar css

**Comment by shyim** [comment]
The JS issues is now fixed in the latest version. I also added the css file instead of compiling theme.

If you have still problems, please reopen the issues :)
