### ISSUE TITLE
Install via composer fails

### ISSUE THREAD

**Issue by 4typen** [shyim/shopware-profiler#41]
Hi,

After installing the profiler via composer Shopware/PHP throws an error 500. Message:

    PHP Warning:  require(/home/vagrant/www/shopware/vendor/composer/../../tests/dbunit_shims.php): failed to open stream: No such file or directory in 
    /home/vagrant/www/shopware/vendor/composer/autoload_real.php on line 70

Maybe the package on packagist is broken?

**Comment by shyim** [comment]
I guess there was a problem with dbunit_shim in the last shopware versions with git.
Can you try the newest version with git?

**Comment by shyim** [comment]
I tested myself. Its a shopware issues with composer.json. The tests folder is not included in release version. You need to add to your command "--no-dev"
