### ISSUE TITLE
Plugin overwrites my xdebug.var_display_max_depth

### ISSUE THREAD

**Issue by cs-mitho** [shyim/shopware-profiler#45]
In my local php.ini I have set xdebug.var_display_max_depth = 10.
But your plugin overwrites this setting to 2. 

Apparently this happens in ShyimProfiler\Components\Event\EventManager in several methods. 

And unfortunately, when hardcoding it to 3 or higher (e. g. in notify()), the loading of the frontend on my test shop results in a blank page.

When deactivating your plugin the setting from my php.ini is used correctly.

**Comment by shyim** [comment]
Could you try the develop branch?

**Comment by cs-mitho** [comment]
I have, it works with the develop branch, thanks!
