### ISSUE TITLE
Error on blocks in classes

### ISSUE THREAD

**Issue by dmetzler1988** [shyim/shopware-profiler#48]
Shopware version 5.3.0

On same places there are `{block}` elements in html classes. This profiler seems to set to each `{block}` element a comment. In the case of block in classes, the classes will be "disabled" with the comment.

On product detail page - the `content-main` container with border around the product will not show the border, if this profiler is active.  

**With shyim shopware profiler:**
```html
<section class="<!-- BLOCK BEGIN frontend_index_content_main_classes, File: /Users/daniel.metzler/sandbox/shopware/seniturn.shop.dev/themes/Frontend/Bare/frontend/plugins/seo/index.tpl -->content-main container block-group<!-- BLOCK END frontend_index_content_main_classes -->">
```

**Without shyim shopware profiler:**
```html
<section class="content-main container block-group">
```

Can you please fix this issue?  
Maybe check if the block is in a class. If yes, don't add a comment.

**Comment by shyim** [comment]
Hey, i added a adjustment to the master branch. Could try again with the master branch?

**Comment by dmetzler1988** [comment]
I will try it today - thanks for fast response :)

**Comment by shyim** [comment]
Its included in release https://github.com/shyim/shopware-profiler/releases/tag/1.1.2
