### ISSUE TITLE
Broken composer.json

### ISSUE THREAD

**Issue by ftdysa** [shyim/shopware-profiler#51]
Hi,

I'm not sure if you meant to do this, but I believe that commit https://github.com/shyim/shopware-profiler/commit/44d95e9df244f374656242c729b60bf7b03d94cb introduced a bug. You are "replacing" symfony/polyfill-mbstring which is causing my satis install to fail with this error:

```
Reading /xxxx/.composer/repo/https---packagist.org/provider-symfony$polyfill-mbstring.json from cache


                                                                                                                                                                                      
  [RuntimeException]                                                                                                                                                                  
  Could not load package shyim/shopware-profiler in https://packagist.org: [UnexpectedValueException] Could not parse version constraint ^v1.2.17: Invalid version string "^v1.2.17" 
```

Would you mind reverting this change?

**Comment by shyim** [comment]
I will revert it later back. I added the line to  remove duplicate packages (Shopware composer and plugin composer)

**Comment by ftdysa** [comment]
This is currently breaking my satis builds .... would you take a pull request to revert it for now?

**Comment by ftdysa** [comment]
It'd be great if you would accept https://github.com/shyim/shopware-profiler/pull/52 for now. Thanks!

**Comment by ftdysa** [comment]
Actually, it looks like this may have been due to a bug in a previous version of satis/composer. I just updated my satis install to the latest version and it appears to be dumping packages again. I'll go ahead and close this task + the pull request for now.
