### ISSUE TITLE
Bock Comment in section class

### ISSUE THREAD

**Issue by fogyhouse** [shyim/shopware-profiler#54]
![screenshot_78](https://user-images.githubusercontent.com/3226700/31498996-bffb0660-af63-11e7-856e-0c096a9f7e70.jpg)

**Comment by shyim** [comment]
I cannot reproduce this issue on latest version. Are you on the latest version?

**Comment by fogyhouse** [comment]
OK. I had the version 1.1.1
Many Thanks
