### ISSUE TITLE
Probleme mit Subshops

### ISSUE THREAD

**Issue by buddhaCode** [shyim/shopware-profiler#56]
Moin Shyim,
danke für dein Plugin. Ich liebe es ;)
Ich habe gerade ein Problem mit Subshops. Der Hauptshop läuft auf gartenhaus.local. Ich profile eine Seite in dem Shop. Welche ist egal. Die Links in deiner Toolbar verweisen aber auf gartenhaus.ch.local. Das wäre in dem Fall einer Subshops. Auf unserer Testumgebung ist es das gleiche. SW Version ist 5.3.4. Dein Plugin ist 1.1.4.
Viele Grüße
Arne

**Comment by buddhaCode** [comment]
Jetzt funktioniert es richtig. Merkwürdig...

**Comment by shyim** [comment]
@buddhaCode Ich werds mir trotzdem später mal anschauen. Eigentlich müsste der link passen, da die URL ganz normal mit dem smarty plugin url generiert wird..
