### ISSUE TITLE
Cycling URL

### ISSUE THREAD

**Issue by riegerjan** [shyim/shopware-profiler#62]
On shopware v.5.3.4. and Intelligente suche v.2.4.1. when I set a synonym group with name "XY" and add a synonym "XY" in it - then save, on frontend when I write "XY" into input search field, there will show some product matchs and on the bottom:
"> Alle Ergebnisse anzeigen"

Clicking on the link on the bottom will load page with URL:
"...../search/index/sSearch/XY" but there comes a problem. URL is cyclic reloaded and growing to:
"...../search/index/sSearch/XY/XY/XY/XY....." endlessly

Renaming synonym group didn't help.

When I remove the synonym with identical name as name of the group, this problem will not occure, on older version of the plugin was necessary have added the synonym with name "XY" in group named "XY". 

Can someone please explain me, what has chenged with the new version about this matter? How does work assignment groups to products or basic functionality of these groups?

Thank you.

**Comment by shyim** [comment]
It's not a problem with the profiler. Please create a ticket in your shopware account.
